### ISSUE TITLE
CKEditor 4.5.10 InvalidCharacterError: String contains an invalid character

### ISSUE THREAD

**Issue by sektor12** [w8tcha/CKEditor-CodeMirror-Plugin#101] opened 2016-07-27 14:56 UTC
When clicking on source, nothing happens, only error in console:

InvalidCharacterError: String contains an invalid character
...b){var c=this.$.className;c&&(a(c,b)||(c+=" "+b));this.$.className=c||b;return t...

When disabling codemirror, source works by default

**Comment by w8tcha** [comment] 2016-07-28 15:02
I published a new version 1.14 with the latest CodeMirror. Can you reproduce the issue with that version?

**Comment by chipncharge** [comment] 2016-10-05 20:53
I am experiencing this same issue using CKEditor 4.5.11 and 1.14 version of CodeMirror. Full message:

ckeditor.js:83 Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('cke_source cke_reset cke_enable_context_menu') contains HTML space characters, which are not valid in tokens.

**Comment by oucil** [comment] 2017-03-09 15:57
This error is still present in 4.6 and 1.16.

**Comment by oucil** [comment] 2017-03-09 16:05
Also noticed this related issue #86 which suggested that the download from CK is out of date, so I tried downloading 1.16 directly from GitHub, no difference. :(

**Comment by w8tcha** [comment] 2017-03-10 17:18
Does this happen in all browsers?

**Comment by oucil** [comment] 2017-03-15 18:17
@w8tcha Sorry, but I can no longer reproduce the error!?!?!  I had tried flushing all caches, reinstalling, then removing and reinstalling the plugin, restarting browsers, everything, but nothing affected it.  I don't any minifiers or anything else that would affect scripts, so really unsure as to the original root cause.  I'll update if it happens again.

**Comment by w8tcha** [comment] 2017-06-25 14:00
okay i close the issue for now

**Closed by w8tcha** 2017-06-25 14:00 UTC
