### ISSUE TITLE
No keyboard accessibility with CodeMirror Plugin

### ISSUE THREAD

**Issue by mondjunge** [w8tcha/CKEditor-CodeMirror-Plugin#203] opened 2023-07-10 11:42 UTC
When using the CodeMirror Plugin, the Ckeditor Accesibility rules won't apply. The CodeMirror Source Area is not reachable with the keyboard and not leaveable with the keyboard.

I would expect to be able to enter the source area from the toolbar with ESC and leave the source area to the toolbar with Alt+F10, when Codemirror Plugin is activated.

**Comment by w8tcha** [comment] 2023-07-11 04:56
Are you referring to the source dialog or the source area? I was not able to reproduce this with the normal source without the codemirror to enter the source mode with esc and close it with alt+f10

**Comment by mondjunge** [comment] 2023-07-11 07:38
I am refering to the source area on ckeditor version 4.21 and up and the Ckeditor Accessibility Support laided out here: https://ckeditor.com/docs/ckeditor4/latest/guide/dev_a11y.html.
ALT+S is none of the. 

Without Codemirror Plugin:
* Tab into WYSIWYG Area
* Press ALT+F10 to Enter the toolbar
* Activate Source with SPACE
* Press ESC to enter the source area
* Press ALT+10 to enter the Toolbar again.
-> Everything fine

With Codemirror Plugin:
* Tab into WYSIWYG Area
* Press ALT+F10 to Enter the toolbar
* Activate Source with SPACE
* You are trapped in the toolbar until deactivating Source. No Accessibility support.

**Closed** 2023-07-11 09:41 UTC

**Comment by w8tcha** [comment] 2023-07-11 09:45
I was able to reproduce it and fix it. But still i would recommend using Alt-S to open/close the source mode it requires less steps..

1. Tab into WYSIWYG Area
2. Press ALT+S to go to directly Source Mode (and with textselection plugin it maintains the cursor position)
